name: Build and Publish to NuGet

on:
  push:
    branches:
      - stop
  pull_request:
    branches:
      - stop

jobs:
  build-and-publish:
    if: github.repository == 'Sichii/Chaos-Server'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Set your .NET Core version here

      - name: Pack
        run: dotnet pack --configuration Release -o nupkgs

      - name: Publish to NuGet
        run: |
          dotnet nuget push "nupkgs/**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
          dotnet nuget push "nupkgs/**/*.snupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json